# Generated by Django 3.2.4 on 2021-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=500)),
                ('body', models.CharField(default='', max_length=10000)),
                ('rank', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, max_length=6)),
                ('image_file', models.ImageField(default='default.jpg', max_length=700, upload_to='media')),
                ('image_url', models.URLField(default='www.noimage.com', max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
