# Generated by Django 3.2.4 on 2021-06-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
