# Generated by Django 3.2.4 on 2021-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0004_auto_20210615_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jyptesttable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'jyptesttable',
                'managed': False,
            },
        ),
    ]
