# Generated by Django 3.2.4 on 2021-06-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0010_cpproduct_cpreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvProduct',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pd_index', models.IntegerField(blank=True, db_column='PD_INDEX', null=True)),
                ('keyword', models.CharField(blank=True, db_column='KEYWORD', max_length=50, null=True)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('review_count', models.IntegerField(blank=True, db_column='REVIEW_COUNT', null=True)),
                ('reg_date', models.CharField(blank=True, db_column='REG_DATE', max_length=15, null=True)),
                ('seller_name', models.CharField(blank=True, db_column='SELLER_NAME', max_length=20, null=True)),
                ('is_ad', models.CharField(blank=True, db_column='IS_AD', max_length=5, null=True)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=20, null=True)),
                ('prod', models.CharField(blank=True, db_column='PROD', max_length=20, null=True)),
                ('link', models.CharField(blank=True, db_column='LINK', max_length=500, null=True)),
                ('score_avg', models.DecimalField(blank=True, db_column='SCORE_AVG', decimal_places=2, max_digits=2, null=True)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=500, null=True)),
            ],
            options={
                'db_table': 'NV_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvReview',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pd_index', models.IntegerField(blank=True, db_column='PD_INDEX', null=True)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=20, null=True)),
                ('review_text', models.CharField(blank=True, db_column='REVIEW_TEXT', max_length=500, null=True)),
                ('score', models.IntegerField(blank=True, db_column='SCORE', null=True)),
                ('p_option', models.CharField(blank=True, db_column='P_OPTION', max_length=100, null=True)),
                ('review_date', models.CharField(blank=True, db_column='REVIEW_DATE', max_length=150, null=True)),
            ],
            options={
                'db_table': 'NV_REVIEW',
                'managed': False,
            },
        ),
    ]
