# Generated by Django 3.2.4 on 2021-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0011_nvproduct_nvreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('pd_manager', models.CharField(blank=True, db_column='PD_MANAGER', max_length=5, null=True)),
                ('pd_code', models.CharField(blank=True, db_column='PD_CODE', max_length=12, null=True)),
                ('pd_name', models.CharField(blank=True, db_column='PD_NAME', max_length=45, null=True)),
                ('pd_brand', models.CharField(blank=True, db_column='PD_BRAND', max_length=12, null=True)),
                ('pd_keyword', models.CharField(blank=True, db_column='PD_KEYWORD', max_length=12, null=True)),
                ('nv_code', models.CharField(blank=True, db_column='NV_CODE', max_length=45, null=True)),
                ('nv_url', models.CharField(blank=True, db_column='NV_URL', max_length=4000, null=True)),
                ('cp_url', models.CharField(blank=True, db_column='CP_URL', max_length=4000, null=True)),
            ],
            options={
                'db_table': 'PRODUCT_MASTER',
                'managed': False,
            },
        ),
    ]
