# Generated by Django 3.2.4 on 2021-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0012_productmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emokeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('analysis_date', models.DateField()),
                ('keyword', models.CharField(max_length=1000)),
                ('key_grade', models.IntegerField()),
                ('emo', models.IntegerField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'EmoKeyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emosentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('prod_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('analysis_date', models.DateField()),
                ('sentence', models.CharField(max_length=4000)),
                ('emo', models.IntegerField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'EmoSentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('match', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('company_check', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('grade', models.IntegerField()),
                ('sales', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('writer', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('regist_date', models.DateField()),
                ('review', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=4000)),
                ('prod_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('option', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('prop_result', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('emo_result', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('emo_grade', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'ReviewData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalkeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
                ('prod_id', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
                ('analysis_date', models.DateField()),
                ('keyword', models.CharField(max_length=1000)),
                ('key_grade', models.FloatField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'TotalKeyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('prod_status', models.IntegerField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('material', models.IntegerField()),
                ('design', models.IntegerField()),
                ('one_point', models.IntegerField()),
                ('two_point', models.IntegerField()),
                ('three_point', models.IntegerField()),
                ('four_point', models.IntegerField()),
                ('five_point', models.IntegerField()),
                ('review_count', models.IntegerField()),
            ],
            options={
                'db_table': 'TotalResult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalsentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('analysis_date', models.DateField()),
                ('sentence', models.CharField(max_length=4000)),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'TotalSentence',
                'managed': False,
            },
        ),
    ]
