# Generated by Django 3.2.8 on 2021-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0013_emokeyword_emosentence_reviewdata_totalkeyword_totalresult_totalsentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_c_Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pd_index', models.IntegerField(db_column='PD_INDEX')),
                ('change_index', models.IntegerField(db_column='CHANGE_INDEX')),
                ('company', models.IntegerField(db_column='COMPANY')),
                ('pd_code', models.CharField(blank=True, db_column='PD_CODE', max_length=50, null=True)),
                ('keyword', models.CharField(db_column='KEYWORD', max_length=50)),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('state', models.CharField(db_column='STATE', max_length=30)),
                ('page_link', models.CharField(db_column='PAGE_LINK', max_length=500)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=50)),
                ('price', models.IntegerField(db_column='PRICE')),
                ('review_count', models.IntegerField(db_column='REVIEW_COUNT')),
                ('image_link', models.TextField(db_column='IMAGE_LINK')),
                ('item_id', models.CharField(db_column='ITEM_ID', max_length=50)),
                ('grade', models.CharField(db_column='GRADE', max_length=5)),
                ('date_info', models.CharField(db_column='DATE_INFO', max_length=50)),
            ],
            options={
                'db_table': 'cp_product',
                'ordering': ['-grade'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cp_review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=50)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=50)),
                ('date', models.DateField(db_column='DATE')),
                ('grade', models.IntegerField(db_column='GRADE')),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('review', models.TextField(db_column='REVIEW')),
            ],
            options={
                'db_table': 'cp_review',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CpProduct',
        ),
        migrations.DeleteModel(
            name='CpReview',
        ),
        migrations.AlterModelTable(
            name='nvproduct',
            table='nv_product',
        ),
        migrations.AlterModelTable(
            name='nvreview',
            table='nv_review',
        ),
        migrations.AlterModelTable(
            name='productmaster',
            table='product_master',
        ),
    ]
