# Generated by Django 3.2.6 on 2021-09-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emokeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('analysis_date', models.DateField()),
                ('keyword', models.CharField(max_length=1000)),
                ('key_grade', models.IntegerField()),
                ('emo', models.IntegerField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'EmoKeyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emosentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('prod_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('analysis_date', models.DateField()),
                ('sentence', models.CharField(max_length=4000)),
                ('emo', models.IntegerField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'EmoSentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvProduct',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rank_num', models.IntegerField(blank=True, db_column='RANK_NUM', max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, db_column='KEYWORD', max_length=50, null=True)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('review_count', models.IntegerField(blank=True, db_column='REVIEW_COUNT', null=True)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=20, null=True)),
                ('prod', models.CharField(blank=True, db_column='PROD', max_length=20, null=True)),
                ('link', models.CharField(blank=True, db_column='LINK', max_length=500, null=True)),
                ('score_avg', models.CharField(blank=True, db_column='SCORE_AVG', max_length=5, null=True)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=500, null=True)),
                ('item_states', models.CharField(blank=True, db_collation='ITEM_STATES', max_length=500, null=True)),
                ('date_info', models.DateTimeField(blank=True, db_column='DATE_INFO', null=True)),
            ],
            options={
                'db_table': 'NV_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvReview',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pd_index', models.IntegerField(blank=True, db_column='PD_INDEX', null=True)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=20, null=True)),
                ('review_text', models.CharField(blank=True, db_column='REVIEW_TEXT', max_length=500, null=True)),
                ('score', models.IntegerField(blank=True, db_column='SCORE', null=True)),
                ('p_option', models.CharField(blank=True, db_column='P_OPTION', max_length=100, null=True)),
                ('review_date', models.CharField(blank=True, db_column='REVIEW_DATE', max_length=150, null=True)),
            ],
            options={
                'db_table': 'NV_REVIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('match', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('company_check', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('grade', models.IntegerField()),
                ('sales', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('writer', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('regist_date', models.DateField()),
                ('review', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=4000)),
                ('prod_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('option', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('prop_result', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('emo_result', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=1000)),
                ('emo_grade', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'ReviewData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalkeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
                ('prod_id', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
                ('analysis_date', models.DateField()),
                ('keyword', models.CharField(max_length=1000)),
                ('key_grade', models.FloatField()),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'TotalKeyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('prod_status', models.IntegerField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('material', models.IntegerField()),
                ('design', models.IntegerField()),
                ('one_point', models.IntegerField()),
                ('two_point', models.IntegerField()),
                ('three_point', models.IntegerField()),
                ('four_point', models.IntegerField()),
                ('five_point', models.IntegerField()),
                ('review_count', models.IntegerField()),
            ],
            options={
                'db_table': 'TotalResult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalsentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=1000)),
                ('prod_id', models.CharField(max_length=1000)),
                ('analysis_date', models.DateField()),
                ('sentence', models.CharField(max_length=4000)),
                ('prod_status', models.CharField(db_collation='utf8_unicode_ci', max_length=1000)),
            ],
            options={
                'db_table': 'TotalSentence',
                'managed': False,
            },
        ),
    ]
