# Generated by Django 3.2.4 on 2021-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_navercrawlertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navercrawlertask',
            name='num_beans',
        ),
        migrations.AddField(
            model_name='navercrawlertask',
            name='key_word',
            field=models.CharField(default='생활낙원', max_length=256),
        ),
    ]
