# Generated by Django 3.2.4 on 2021-07-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_coupangcrawlertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangcrawlertask',
            name='key_word',
            field=models.CharField(default='생확낙원 예상요청 결과물', max_length=256),
        ),
    ]
