# Generated by Django 3.2.4 on 2021-07-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_coupangcrawlertask_key_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupangcrawlertask',
            name='key_word',
            field=models.CharField(default='생낙', max_length=256),
        ),
    ]
