# Generated by Django 3.2.7 on 2021-10-10 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0013_npcrawlertask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='npcrawlerTask',
            new_name='nccrawlerTask',
        ),
    ]
