# Generated by Django 3.2.4 on 2021-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_C_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_index', models.IntegerField(db_column='PD_INDEX')),
                ('keyword', models.CharField(db_column='KEYWORD', max_length=50)),
                ('title', models.CharField(db_column='TITLE', max_length=200)),
                ('page_link', models.CharField(db_column='PAGE_LINK', max_length=500)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=50)),
                ('price', models.IntegerField(db_column='PRICE')),
                ('review_count', models.IntegerField(db_column='REVIEW_COUNT')),
                ('image_link', models.TextField(db_column='IMAGE_LINK')),
                ('item_id', models.CharField(db_column='ITEM_ID', max_length=50)),
            ],
            options={
                'db_table': 'CP_C_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crawling_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=100)),
                ('index_num', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=500)),
                ('pid', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('image_path', models.URLField(default='www.noimage.com', max_length=700)),
                ('vendor_itemID', models.IntegerField(default=0)),
            ],
        ),
    ]
