# Generated by Django 3.2.4 on 2021-06-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0005_alter_cp_c_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawling_item',
        ),
    ]
