# Generated by Django 3.2.7 on 2021-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriCmk',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('coupang_cids', models.CharField(blank=True, max_length=255, null=True)),
                ('first_class_name', models.CharField(max_length=255)),
                ('naver_cids', models.CharField(blank=True, max_length=255, null=True)),
                ('second_class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('glowpick_cids', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categori_cmk',
                'managed': False,
            },
        ),
    ]
