# Generated by Django 3.2.7 on 2021-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowpick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmkCtest',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cmk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('second_class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_class', models.CharField(blank=True, max_length=50, null=True)),
                ('productid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('ranking', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('review_count', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredientlist', models.CharField(blank=True, max_length=500, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('imgpath', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'cmk_ctest',
                'managed': False,
            },
        ),
    ]
