# Generated by Django 3.2.7 on 2021-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowpick', '0002_cmkctest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmkCrtest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmk_id', models.CharField(blank=True, max_length=30, null=True)),
                ('productid', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_age', models.CharField(blank=True, max_length=30, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user_star', models.CharField(blank=True, max_length=10, null=True)),
                ('review_create_date', models.CharField(blank=True, max_length=100, null=True)),
                ('review_content', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'cmk_crtest',
                'managed': False,
            },
        ),
    ]
