# Generated by Django 3.2.7 on 2021-10-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowpick', '0004_cmkbrtest_cmkbtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmkCpProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmk_id', models.CharField(blank=True, max_length=50, null=True)),
                ('second_class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cp_class', models.CharField(blank=True, max_length=50, null=True)),
                ('cp_class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('productid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('ranking', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('review_count', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=5000, null=True)),
                ('imgpath', models.CharField(blank=True, max_length=5000, null=True)),
                ('date_info', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cmk_cp_product',
                'managed': False,
            },
        ),
    ]
