# Generated by Django 3.2.7 on 2021-10-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowpick', '0007_cmknvproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmkNvReview',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('productid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('item_option', models.CharField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_star', models.CharField(blank=True, max_length=10, null=True)),
                ('review_create_date', models.CharField(blank=True, max_length=30, null=True)),
                ('review_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cmk_nv_review',
                'managed': False,
            },
        ),
    ]
