# Generated by Django 3.2.8 on 2021-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('pd_manager', models.CharField(blank=True, db_column='PD_MANAGER', max_length=5, null=True)),
                ('pd_code', models.CharField(blank=True, db_column='PD_CODE', max_length=12, null=True)),
                ('pd_name', models.CharField(blank=True, db_column='PD_NAME', max_length=45, null=True)),
                ('pd_brand', models.CharField(blank=True, db_column='PD_BRAND', max_length=12, null=True)),
                ('pd_keyword', models.CharField(blank=True, db_column='PD_KEYWORD', max_length=12, null=True)),
                ('nv_code', models.CharField(blank=True, db_column='NV_CODE', max_length=45, null=True)),
                ('nv_url', models.CharField(blank=True, db_column='NV_URL', max_length=4000, null=True)),
                ('cp_code', models.CharField(blank=True, db_column='CP_CODE', max_length=50, null=True)),
                ('cp_url', models.CharField(blank=True, db_column='CP_URL', max_length=4000, null=True)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=4000, null=True)),
            ],
            options={
                'db_table': 'product_master',
                'managed': False,
            },
        ),
    ]
